#!/bin/bash

#-- FONT COLOR
RED='\033[1;31m'
GREEN='\033[1;32m'
MAGENTA='\033[1;35m'
NOCOLOR='\033[1;m'

clear
echo " "

if [ -x /usr/bin/dfc ]
	then 
		echo "                     =======================";
		echo -e "                      $MAGENTA  FREE SYSTEM FILES  $NOCOLOR";
		echo "                     =======================";
		echo " ";
		dfc -dp -/dev/loop,tmpfs;

else 
	echo -n -e "$>$RED [DFC] is not installed on your system.
    Do you want to install it (y/n) ? $NOCOLOR";
		
	read -r answer
	echo " "
	if [ $answer == 'y' ]
		then 
			echo -e "$>$MAGENTA DFC$NOCOLOR installation in progress..."
			echo " "
			sudo apt install -y dfc
			echo " "
			echo -e "$>$MAGENTA DFC$NOCOLOR installation =>$GREEN DONE !$NOCOLOR"
	else 
		exit 0	
	fi
fi
