#!/bin/bash

#-- FONT COLOR
RED='\033[1;31m'
CYAN='\033[1;36m'
NOCOLOR='\033[1;m'

clear
echo " "

if [ -x /usr/bin/exa ]
	then
		if [ ! -z "$@" ]
			then
				echo -e "$> List of items contained in $CYAN$@$NOCOLOR"
				echo " "
 				exa -ahli "$@"
		else
    			echo -ne "$> List of items contained in the current path : $CYAN"
				pwd
				echo -e "$NOCOLOR"
				exa -ahli "$@"
 		fi

else
	echo -ne "$RED [EXA] is not installed on your system.
Do you want to install it (y/n) ? $NOCOLOR"
	
	read -r answer;
	echo " "
	if [ $answer == 'y' ]
		then
			sudo apt install -y exa
	else
		exit 0	
	fi
fi

# [if [ ! -z "$@" ]] : If string is not empty. 
# [!] = different // -z = zero // -n = non-zero

# "$@" Allows to type any argument behind the command
