#!/bin/bash

#-- FONT COLOR
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[1;35m'
NOCOLOR='\033[1;m'

#----------------------------------------------------------
menu()
{
	clear
	echo " "
	echo "$> Choose the folder to go : "
	echo -e "    1.$MAGENTA Eloise    $NOCOLOR"
	echo -e "    2.$MAGENTA Tiffany   $NOCOLOR"
	echo -e "    3.$MAGENTA Mega      $NOCOLOR"
	echo -e "    4.$MAGENTA Git       $NOCOLOR"
	echo -e "    5.$MAGENTA Local/bin $NOCOLOR"
	echo " "
	echo -e "    x.$MAGENTA Exit      $NOCOLOR"
	echo " "
	echo -n "    >> "
	read -r choice
	echo " "
}
#==========================================================
menu
while true
do
	if [ $choice == '1' ]
		then 
			cd /media/ayckinn/ELOISE
			exec zsh

	elif [ $choice == '2' ]
		then 
			cd /media/ayckinn/TIFANNY
			exec zsh

	elif [ $choice == '3' ]
		then 
			cd /media/ayckinn/ELOISE/MEGA
			exec zsh

	elif [ $choice == '4' ]
		then
			cd /media/ayckinn/ELOISE/GIT
			exec zsh

	elif [ $choice == '5' ]
		then
			cd /usr/local/bin
			exec zsh

	elif [ $choice == 'x' ]
		then
			echo -e "$GREEN    See you soon... $NOCOLOR" 
			break

	else
		echo -e "$RED    Wrong choice ! $NOCOLOR"
		sleep 2
		menu
	fi
done


# Replace [exec zsh]  to [exec bash] if you use the bash