#!/bin/bash

PURPLE='\033[1;35m'
GREEN='\033[1;32m'
NOCOLOR='\033[1;m'

clear

echo " "
echo -e "=>$PURPLE DOWNLOAD AND ADD THE SUBLIME-TEXT KEY $NOCOLOR"
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add
echo " "
echo -e "=>$PURPLE DOWNLOAD [APT-TRANSPORT-HTTPS] $NOCOLOR"
sudo apt-get install apt-transport-https
echo " "
echo -e "=>$PURPLE ADD SUBLIME-TEXT REPO TO THE SOURCE LIST FOLDER $NOCOLOR"
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
echo " "
echo -e "=>$PURPLE UPDATE DATABASE $NOCOLOR"
sudo apt update
echo " "
echo -e "=>$PURPLE SUBLIME-TEXT INSTALL ==>$GREEN DONE ! $NOCOLOR"